# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-10 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('app_tpye', models.CharField(choices=[('fat', 'Fat Client'), ('web', 'Web Client')], max_length=20)),
                ('has_interface', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('schedule_tpye', models.CharField(choices=[('triggered', 'Event triggered'), ('timely', 'Timely scheduled')], max_length=20)),
                ('exec_duration_man', models.IntegerField(default=0)),
                ('exec_duration_auto', models.IntegerField(default=0)),
                ('instance_count_monthly', models.IntegerField(default=0)),
                ('panel_count', models.IntegerField(default=0)),
                ('input_field_count', models.IntegerField(default=0)),
                ('button_count', models.IntegerField(default=0)),
                ('dropdown_count', models.IntegerField(default=0)),
                ('checkbox_count', models.IntegerField(default=0)),
                ('radio_button_count', models.IntegerField(default=0)),
                ('file_input_count', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.Application')),
                ('processes', models.ManyToManyField(blank=True, to='processes.Process')),
            ],
        ),
    ]
