# Generated by Django 2.1 on 2018-08-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_auto_20180813_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetask',
            name='gateway_count',
            field=models.IntegerField(default=0),
        ),
    ]
