# Generated by Django 2.1 on 2018-08-20 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_auto_20180817_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetask',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.Application'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
