# Generated by Django 2.1 on 2018-08-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalcSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('size_m', models.IntegerField(default=25)),
                ('size_l', models.IntegerField(default=100)),
                ('effort_factor_s', models.FloatField(default=1)),
                ('effort_factor_m', models.FloatField(default=1.5)),
                ('effort_factor_l', models.FloatField(default=3)),
                ('panel_base_effort', models.IntegerField(default=0)),
                ('input_field_base_effort', models.IntegerField(default=0)),
                ('button_base_effort', models.IntegerField(default=0)),
                ('dropdown_base_effort', models.IntegerField(default=0)),
                ('checkbox_base_effort', models.IntegerField(default=0)),
                ('radio_button_base_effort', models.IntegerField(default=0)),
                ('file_input_base_effort', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
