# Generated by Django 2.1 on 2018-08-20 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('calcschemas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcschema',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.Application'),
        ),
    ]
